name: Deploy back on Lambda

on:
  push:
    branches:
      - main
    paths:
      - "back/**"
      - ".github/workflows/back_deploy.yml"

jobs:
  deploy_on_lambda:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: Deploy on Lambda
    steps:
      # main ブランチを取得する
      - name: Checkout
        uses: actions/checkout@v3

      # AWSへ接続する
      - name: Assuming AWS role with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "ap-northeast-1" # リージョンを指定
          role-to-assume: "arn:aws:iam::851725478795:role/mapapp-iam-github-role" # 作成した IAM ロールの ARN

      # /back/lambda 配下の全ディレクトリに対してディレクトリ名を Lambda 関数名としてzip化しデプロイする
      - name: Deploy Lambda functions
        run: |
          for dir in */; do
            func=${dir%/}
            pushd "$dir"
            zip -r deploy.zip ./index.mjs
            aws lambda update-function-code --function-name "$func" --zip-file fileb://deploy.zip
            popd
          done
        working-directory: ./back/lambda
