name: Deploy front on S3

on:
  push:
    branches:
      - main

jobs:
  vue_build_and_deploy_on_s3:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: Vue build and deploy on S3
    steps:
      # main ブランチを取得する
      - name: Checkout
        uses: actions/checkout@v3

      # Node.js のセットアップをする
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: "./front/"

      # パッケージをインストールする
      - name: Install dependencies
        run: npm ci
        working-directory: ./front

      # .envファイルを作成する
      - name: Create .env.local
        run: |
          touch .env.local
          echo VUE_APP_MAPS_API_KEY=${{ secrets.VUE_APP_MAPS_API_KEY }} >> .env.local
        working-directory: ./front

      # ビルドする
      - name: Build
        run: npm run build
        working-directory: ./front

      # AWSへ接続する
      - name: Assuming AWS role with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "ap-northeast-1" # リージョンを指定
          role-to-assume: "arn:aws:iam::851725478795:role/mapapp-iam-github-role" # 作成した IAM ロールの ARN

      # デプロイする
      - name: Deploy
        run: aws s3 cp --recursive --region ap-northeast-1 dist s3://mapapp-bucket
        working-directory: ./front
